# -*- coding: utf-8 -*-
"""assignment3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HjZACkGHtHBMI_gyxqn166CYVbeq4xd-

1.1 write a program to implement your own myreduce() function which works exactly
like Python's built-in function reduce()
"""

def func(n):
    return n%2==0    
def myfilter(func,l):
    l1=[]
    for i in l:
        if func(i):
            l1.append(i)
    print(l1)
li=[2,3,4,5,6,7,8,5,2,4,1]
myfilter(func,li)

"""1.2 Write a Python program to implement your own myfilter() function which works exactly
like Python's built-in function filter()
"""

def infunc(a,b):
    return a+b

def myreduce(func,l):
    sm=0
    for i in l:
        sm=func(sm,i)
    print(sm)
l2=[1,2,3,4,5,6]
myreduce(infunc,l2)

"""2. Implement List comprehensions to produce the following lists.
['x', 'xx', 'xxx', 'xxxx', 'y', 'yy', 'yyy', 'yyyy', 'z', 'zz', 'zzz', 'zzzz']
['x', 'y', 'z', 'xx', 'yy', 'zz', 'xxx', 'yyy', 'zzz', 'xxxx', 'yyyy', 'zzzz']
[[2], [3], [4], [3], [4], [5], [4], [5], [6]] [[2, 3, 4, 5], [3, 4, 5, 6],
[4, 5, 6, 7], [5, 6, 7, 8]]
[(1, 1), (2, 1), (3, 1), (1, 2), (2, 2), (3, 2), (1, 3), (2, 3), (3, 3)]
"""

l=[]
l1=[]
st="xyz"
for i in st:
    for j in range(1,5):
        l.append(i*j)
for i in range(1,5):
    for j in st:
        l1.append(i*j)
print(l)
print(l1)

s=[2,3,4,5,6]
l2=[]
l1=[]
for i in range(len(s)-2):
    for j in range(i,i+3):
        l2.append([s[j]])
print(l2)
#2.4
l4=[]
a=[]
l3=[]
s=[2,3,4,5,6,7,8]
for i in range(len(s)-3):
    l=4
    l4.append(s[i:i+l])
print(l4)

t=()
l5=[]
k=[1,2,3]
for i in k:
    for j in k:
        t=(j,i)    
        l5.append(t)
print(l5)